Configuration NewWebBinding
{
    param
	(
        [Parameter(Mandatory = $false)]
		[pscredential]$ComputerName,
        [Parameter(Mandatory = $true)]
		[pscredential]$Credential
	)

    Import-DscResource -ModuleName WebBindingDsc

    Node $ComputerName
    {
        WebBinding NewWebBinding
        {
            Name = $Node.Name
            Protocol = $Node.Protocol
            Port = $Node.Port
            IPAddress = $Node.IPAddress
            HostHeader = $Node.HostHeader
            SslFlags = $Node.SslFlags
            Ensure = 'Present'
            PsDscRunAsCredential = $Credential
        }
    }
}

$ConfigurationData = @{
    AllNodes = @(
        @{
            Name = 'contoso'
            Protocol = 'https'
            Port = '443'
            IPAddress = '192.168.100.100'
            HostHeader = 'www.contoso.com'
            SslFlags = '3' 
            PsDscAllowPlainTextPassword = $true
            PsDscAllowDomainUser = $true
        }
    )
}


# SIG # Begin signature block
# MIIORgYJKoZIhvcNAQcCoIIONzCCDjMCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUMtK4H92QtSfELqX9bdH5nJoO
# XSOgggt+MIIFizCCBHOgAwIBAgIQJG0JIrvaHRFoNN+b4GQU8zANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBB
# cmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjElMCMG
# A1UEAxMcSW5Db21tb24gUlNBIENvZGUgU2lnbmluZyBDQTAeFw0xNjA3MDUwMDAw
# MDBaFw0xOTA3MDUyMzU5NTlaMIHFMQswCQYDVQQGEwJVUzEOMAwGA1UEEQwFMzM2
# MTIxCzAJBgNVBAgMAkZMMQ4wDAYDVQQHDAVUYW1wYTESMBAGA1UECQwJU3VpdGUg
# MTAwMRswGQYDVQQJDBIzNjUwIFNwZWN0cnVtIEJsdmQxJDAiBgNVBAoMG1VuaXZl
# cnNpdHkgb2YgU291dGggRmxvcmlkYTEMMAoGA1UECwwDRVBJMSQwIgYDVQQDDBtV
# bml2ZXJzaXR5IG9mIFNvdXRoIEZsb3JpZGEwggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQC0lA9TBpRbE2esKduC45jNeyEZ2GbQj4Cu4J6Fhdrf4xbgJJBY
# XGEUjex5BfxLj1/J8cDI2zHTY94N6FWDbAbHSaviWR7TyyEUpuFyjqJ7U2wYb42R
# W3UiW+euo6EZIsP021i6LMrtGi31e3LjRCmQyD/P3E/xFG3NPQf7R+GsQYmT+kwT
# dUpTwHWhJuVubOcW1v1bAWg8pKQKfRAqXf/PDlW/idy6IcjSN6fX/6dRPy79qkNK
# mMqC27qU2Kt2UOsR7t9Y6x0Ju4uQprD2nGKXWPD1ptS43HYaOXhT535tA/CNQaf1
# lEbHCQSz/NDFzlZEv4V3+399bM+IH5RSwYkZAgMBAAGjggG9MIIBuTAfBgNVHSME
# GDAWgBSuNSMX//8GPZxQ4IwkZTMecBCIojAdBgNVHQ4EFgQUksSexgxWwlgzyiEV
# ihEMltxPKsswDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwEQYJYIZIAYb4QgEBBAQDAgQQMGYGA1UdIARfMF0wWwYMKwYB
# BAGuIwEEAwIBMEswSQYIKwYBBQUHAgEWPWh0dHBzOi8vd3d3LmluY29tbW9uLm9y
# Zy9jZXJ0L3JlcG9zaXRvcnkvY3BzX2NvZGVfc2lnbmluZy5wZGYwSQYDVR0fBEIw
# QDA+oDygOoY4aHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNB
# Q29kZVNpZ25pbmdDQS5jcmwwfgYIKwYBBQUHAQEEcjBwMEQGCCsGAQUFBzAChjho
# dHRwOi8vY3J0LmluY29tbW9uLXJzYS5vcmcvSW5Db21tb25SU0FDb2RlU2lnbmlu
# Z0NBLmNydDAoBggrBgEFBQcwAYYcaHR0cDovL29jc3AuaW5jb21tb24tcnNhLm9y
# ZzANBgkqhkiG9w0BAQsFAAOCAQEAp2+YsTmkusJg0/pnpWqpKzhsSo4Zw691T5Cr
# 4x6KqDvF7Jl4lAdjpQNcbcQB1/SefturFQITJT92KYvewzQ3nMWj+42xWMPU9fhb
# zE0aPIOYXYCzJbBxNeRuTf95fZ0dtCbO4+LErgfGN+ZtVsD2GR+3ncpVGgFq3J2l
# a4ubLmwdIPwmjPjf8kFPt9brBUTJnPotFVVxdL9WR7sfEebvQVEF8W7/hHzVsNjw
# bwH3aJAZKjfBLugtU26WlEG07bxRF9SgbNOn/Hwas1E+wcZbouqwLf2eHiWM3uAh
# H+A1cO8GpPSy9f6OnkG8gSR3obqqAj6sT4kwicdFMUUhVmllfDCCBeswggPToAMC
# AQICEGXh4uPV3lBFhfMmJIAF4tQwDQYJKoZIhvcNAQENBQAwgYgxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEe
# MBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1
# c3QgUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE0MDkxOTAwMDAwMFoX
# DTI0MDkxODIzNTk1OVowfDELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYD
# VQQHEwlBbm4gQXJib3IxEjAQBgNVBAoTCUludGVybmV0MjERMA8GA1UECxMISW5D
# b21tb24xJTAjBgNVBAMTHEluQ29tbW9uIFJTQSBDb2RlIFNpZ25pbmcgQ0EwggEi
# MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAoC+LHnq7anWs+D7co7o5Isrz
# o3bkv30wJ+a605gyViNcBoaXDYDo7aKBNesL9l5+qT5oc/2d1Gd5zqrqaLcZ2xx2
# OlmHXV6Zx6GyuKmEcwzMq4dGHGrH7zklvqfd2iw1cDYdIi4gO93jHA4/NJ/lff5V
# gFsGfIJXhFXzOPvyDDapuV6yxYFHI30SgaDAASg+A/k4l6OtAvICaP3VAav11VFN
# UNMXIkblcxjgOuQ3d1HInn1Sik+A3Ca5wEzK/FH6EAkRelcqc8TgISpswlS9HD6D
# +FupLPH623jP2YmabaP/Dac/fkxWI9YJvuGlHYsHxb/j31iq76SvgssF+AoJAgMB
# AAGjggFaMIIBVjAfBgNVHSMEGDAWgBRTeb9aqitKz1SA4dibwJ3ysgNmyzAdBgNV
# HQ4EFgQUrjUjF///Bj2cUOCMJGUzHnAQiKIwDgYDVR0PAQH/BAQDAgGGMBIGA1Ud
# EwEB/wQIMAYBAf8CAQAwEwYDVR0lBAwwCgYIKwYBBQUHAwMwEQYDVR0gBAowCDAG
# BgRVHSAAMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0LmNv
# bS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2BggrBgEF
# BQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNvbS9V
# U0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDovL29j
# c3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQ0FAAOCAgEARiy2f2pOJWa9nGqm
# qtCevQ+uTjX88DgnwcedBMmCNNuG4RP3wZaNMEQT0jXtefdXXJOmEldtq3mXwSZk
# 38lcy8M2om2TI6HbqjACa+q4wIXWkqJBbK4MOWXFH0wQKnrEXjCcfUxyzhZ4s6tA
# /L4LmRYTmCD/srpz0bVU3AuSX+mj05E+WPEop4WE+D35OLcnMcjFbst3KWN99xxa
# K40VHnX8EkcBkipQPDcuyt1hbOCDjHTq2Ay84R/SchN6WkVPGpW8y0mGc59lul1d
# lDmjVOynF9MRU5ACynTkdQ0JfKHOeVUuvQlo2Qzt52CTn3OZ1NtIZ0yrxm267pXK
# uK86UxI9aZrLkyO/BPO42itvAG/QMv7tzJkGns1hmi74OgZ3WUVk3SNTkixAqCbf
# 7TSmecnrtyt0XB/P/xurcyFOIo5YRvTgVPc5lWn6PO9oKEdYtDyBsI5GAKVpmrUf
# dqojsl5GRYQQSnpO/hYBWyv+LsuhdTvaA5vwIDM8WrAjgTFx2vGnQjg5dsQIeUOp
# TixMierCUzCh+bF47i73jX3qoiolCX7xLKSXTpWS2oy7HzgjDdlAsfTwnwton5YN
# TJxzg6NjrUjsUbEIORtJB/eeld5EWbQgGfwaJb5NEOTonZckUtYS1VmaFugWUEuh
# SWodQIq7RA6FT/4AQ6qdj3yPbNExggIyMIICLgIBATCBkDB8MQswCQYDVQQGEwJV
# UzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50
# ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjElMCMGA1UEAxMcSW5Db21tb24gUlNB
# IENvZGUgU2lnbmluZyBDQQIQJG0JIrvaHRFoNN+b4GQU8zAJBgUrDgMCGgUAoHgw
# GAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGC
# NwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQx
# FgQU/x4ITIMW6WCi6a3vOSdvPVjcQB8wDQYJKoZIhvcNAQEBBQAEggEApPu7FpmW
# QsFxVhF+gOPTXTeWneo3/chX+AgxMzTT9e+Z3bpkkDWe1iTCDxdTYsJtQzPon+kz
# E4toiX8tmOgq3fqiF/lpwWHcfKuJcPoIWCE54OqaUBPmhRq51dBB26fDvUEoKQuT
# 4QkF3mrGR/qcqzAh0kSggglOWrQWqxU9OPKQGHZfpC6/E3VhC7HxQ4kM/IcJJJKw
# 6lyr9+BoFE6zamFcsFOJDavELk7de334VaFy6s7VTQ8GVV7mBQHYvI5CIyV6ExpD
# g6O9Vn+erA7T4aoNsvg09U9l4txYMXLHwYFCz1DLuh/o9VTF7+3mo6BDeyuoB/M+
# ZcF7VCBzPUeoXA==
# SIG # End signature block
